# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: I-ME studio
# Description of the Site
description: 인천대학교 산업경영공학과 앱개발 소모임
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.news.unn.net/news/photo/202101/503653_303981_349.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: I-ME studio
# URL for the Image of the Author
author-image: /i-me_studio/assets/images/IME 로고.png
# 60 Words About the Author
author-about: 안녕하세요:) 인천대학교 산업경영공학과 앱개발 팀 '<b>I-ME studio</b>' 입니다. <br> 
              2023년 1월 20일 부터 시작된 저희 모임은 김관호 교수님 외 5명으로 이루어져있으며 <br>
              [기획/디자인팀-양서린, 조성훈] , [프론트엔드 개발팀-박정한] , [백엔드 개발팀-김경난, 박은서] 로 구성되었습니다. <br>
              저희 팀은 현재 학교 공지 App 서비스를 개발 중에 있습니다.  문의 사항및 공지사항은 Contact와 Blog를 참고해주시기 바랍니다. 감사합니다:)
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
